# Generated by Django 3.2.9 on 2021-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('price', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
