# Generated by Django 3.2.9 on 2021-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
