# Generated by Django 3.2.9 on 2021-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_rename_note_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='price',
            field=models.FloatField(default=10.5),
            preserve_default=False,
        ),
    ]
