# Generated by Django 3.2.9 on 2021-12-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='content',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='price',
        ),
        migrations.AddField(
            model_name='venda',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.produto'),
        ),
    ]
