# Generated by Django 3.2.9 on 2021-12-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_cost'),
        ('vendas', '0004_auto_20211207_1537'),
    ]

    operations = [
    ]
